### ISSUE TITLE
PermissionError: [WinError 32]

### ISSUE THREAD

**Issue by hyrious** [pitr/sublime-nimpretty#1]
Consider adding `os.close(self.tmpfd)` before `os.remove(self.tmpname)`

Ref. https://stackoverflow.com/questions/45042466/permissionerror-winerror-32-when-trying-to-delete-a-temporary-image

**Comment by pitr** [comment]
thanks. Could you open a PR against this repo?

**Comment by pitr** [comment]
1.0.1 with this fix released
